In [3]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
import numpy as np
import pandas as pd
import seaborn as sns
import pickle

In [4]:
rede_neural = pickle.load(open('rede_neural_finalizado.sav', 'rb'))
arvore = pickle.load(open('arvore_finalizado.sav', 'rb'))
svm = pickle.load(open('svm_finalizado.sav', 'rb'))

In [5]:
with open('credit.pkl', 'rb') as f:  
  X_credit_treinamento, y_credit_treinamento, X_credit_teste, y_credit_teste = pickle.load(f)

In [6]:
X_credit = np.concatenate((X_credit_treinamento, X_credit_teste), axis = 0)
y_credit = np.concatenate((y_credit_treinamento, y_credit_teste), axis = 0)

In [7]:
y_credit

array([0, 0, 0, ..., 0, 1, 1], dtype=int64)

In [8]:
novo_registro = X_credit[0]
novo_registro = novo_registro.reshape(1,-1)
novo_registro, novo_registro.shape

resposta_rede_neural = rede_neural.predict(novo_registro)
resposta_arvore = arvore.predict(novo_registro)
resposta_svm = svm.predict(novo_registro)

In [9]:
resposta_rede_neural[0], resposta_arvore[0], resposta_svm[0]

(0, 0, 0)

In [10]:
probabilidade_rede_neural = rede_neural.predict_proba(novo_registro)
probabilidade_arvore = arvore.predict_proba(novo_registro)
probabilidade_svm = svm.predict_proba(novo_registro)

In [18]:
probabilidade_rede_neural, probabilidade_arvore, probabilidade_svm

(array([[1.0000000e+00, 6.7335216e-18]]),
 array([[1., 0.]]),
 array([[9.99997549e-01, 2.45053294e-06]]))

In [12]:
confianca_rede_neural = probabilidade_rede_neural.max()
confianca_arvore = probabilidade_arvore.max()
confianca_svm = probabilidade_svm.max()

In [17]:
confianca_rede_neural, confianca_arvore, confianca_svm


(1.0, 1.0, 0.9999975494670589)

In [16]:
npaga = paga = algoritmos = 0
conf_minima = 0.999999
if confianca_rede_neural >= conf_minima:
    algoritmos += 1
    if resposta_rede_neural == 1:
            npaga += 1
    else:
        paga +=1

if confianca_arvore >= conf_minima:
    algoritmos += 1
    if resposta_arvore == 1:
        npaga += 1
    else:
        paga += 1

if confianca_svm >= conf_minima:
    algoritmos +=1
    if resposta_svm == 1:
        npaga = 1
    else:
        paga = 1
if paga> npaga:
    print(f'Cliente vai pagar baseado em {algoritmos} algoritmos')
else:
    print('Cliente não vai pagar o empréstimo')
npaga = paga = 0

Cliente vai pagar baseado em 2 algoritmos
