## Regressão polinomial base saude

In [1]:
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from yellowbrick.regressor import ResidualsPlot
from sklearn.metrics import mean_absolute_error

In [2]:
base_plano_saude_2 = pd.read_csv('plano_saude2.csv')
base_plano_saude_2

idade  custo
0     18    470
1     23    520
2     28    630
3     33    830
4     38   1150
5     43   1530
6     48   2040
7     53   3080
8     58   5100
9     63  10100

In [3]:
x_plano_saude_2 = base_plano_saude_2.iloc[:, 0:1].values
x_plano_saude_2

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]], dtype=int64)

In [4]:
y_plano_saude_2 = base_plano_saude_2.iloc[:, 1].values
y_plano_saude_2

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100], dtype=int64)

In [5]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree=3)
x_plano_saude_2_poly = poly.fit_transform(x_plano_saude_2)

In [6]:
x_plano_saude_2_poly

array([[1.00000e+00, 1.80000e+01, 3.24000e+02, 5.83200e+03],
       [1.00000e+00, 2.30000e+01, 5.29000e+02, 1.21670e+04],
       [1.00000e+00, 2.80000e+01, 7.84000e+02, 2.19520e+04],
       [1.00000e+00, 3.30000e+01, 1.08900e+03, 3.59370e+04],
       [1.00000e+00, 3.80000e+01, 1.44400e+03, 5.48720e+04],
       [1.00000e+00, 4.30000e+01, 1.84900e+03, 7.95070e+04],
       [1.00000e+00, 4.80000e+01, 2.30400e+03, 1.10592e+05],
       [1.00000e+00, 5.30000e+01, 2.80900e+03, 1.48877e+05],
       [1.00000e+00, 5.80000e+01, 3.36400e+03, 1.95112e+05],
       [1.00000e+00, 6.30000e+01, 3.96900e+03, 2.50047e+05]])

In [7]:
regressor_saude_polinomial = LinearRegression()
regressor_saude_polinomial.fit(x_plano_saude_2_poly, y_plano_saude_2)

LinearRegression()

In [8]:
regressor_saude_polinomial.intercept_

-9906.403636363324

In [9]:
regressor_saude_polinomial.coef_

array([ 0.00000000e+00,  1.03425888e+03, -3.23049417e+01,  3.30256410e-01])

In [10]:
novo = [[40]]
novo = poly.transform(novo)
novo


array([[1.0e+00, 4.0e+01, 1.6e+03, 6.4e+04]])

In [11]:
regressor_saude_polinomial.predict(novo)

array([912.45510489])

In [12]:
previsoes = regressor_saude_polinomial.predict(x_plano_saude_2_poly)
previsoes

array([ 169.5104895 ,  810.46620046,  975.55944055,  912.48251747,
        868.92773892, 1092.58741258, 1831.15384615, 3332.31934732,
       5843.77622379, 9613.21678324])

In [13]:
grafico = px.scatter(x= x_plano_saude_2[:, 0], y= y_plano_saude_2)
grafico.add_scatter(x= x_plano_saude_2[:, 0], y= previsoes, name='Regressão')
grafico.show()

## Regressão polinomial base casas

In [14]:
base_casas = pd.read_csv('house_prices.csv')
x_casas = base_casas.iloc[:, 3:19].values
y_casas = base_casas.iloc[:, 2].values
from sklearn.model_selection import train_test_split
x_casas_treinamento, x_casas_teste, y_casas_treinamento, y_casas_teste = train_test_split(x_casas, y_casas, test_size=0.3, random_state=0)

In [15]:
x_casas_treinamento.shape, y_casas_treinamento.shape, x_casas_teste.shape, y_casas_teste.shape

((15129, 16), (15129,), (6484, 16), (6484,))

In [16]:
from sklearn.preprocessing import PolynomialFeatures
poly = PolynomialFeatures(degree = 2)
x_casas_treinamento_poly = poly.fit_transform(x_casas_treinamento)
x_casas_teste_poly = poly.transform(x_casas_teste)

In [17]:
x_casas_treinamento_poly.shape, x_casas_teste_poly.shape

((15129, 153), (6484, 153))

In [18]:
from sklearn.linear_model import LinearRegression
regressor_casas_poly = LinearRegression()
regressor_casas_poly.fit(x_casas_treinamento, y_casas_treinamento)


LinearRegression()

In [38]:
regressor_casas_poly.score(x_casas_treinamento_poly, y_casas_treinamento)

ValueError: X has 153 features, but LinearRegression is expecting 16 features as input.

In [39]:
regressor_casas_poly.score(x_casas_teste_poly, y_casas_teste)

ValueError: X has 153 features, but LinearRegression is expecting 16 features as input.

In [40]:
previsoes = regressor_casas_poly.predict(x_casas_teste_poly)
previsoes

ValueError: X has 153 features, but LinearRegression is expecting 16 features as input.

In [21]:
y_casas_teste

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [22]:
from sklearn.metrics import mean_absolute_error, mean_squared_error


In [41]:
mean_absolute_error(y_casas_teste, previsoes)


100035.18036705737

## Regressão com árvores de decisão

In [24]:
x_plano_saude_2

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]], dtype=int64)

In [25]:
y_plano_saude_2


array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100], dtype=int64)

In [42]:
from sklearn.tree import DecisionTreeRegressor
regressor_arvore_saude = DecisionTreeRegressor()
regressor_arvore_saude.fit(x_plano_saude_2, y_plano_saude_2)


DecisionTreeRegressor()

In [27]:
previsoes = regressor_arvore_saude.predict(x_plano_saude_2)
previsoes

array([  470.,   520.,   630.,   830.,  1150.,  1530.,  2040.,  3080.,
        5100., 10100.])

In [28]:
regressor_arvore_saude.score(x_plano_saude_2, y_plano_saude_2)

1.0

In [29]:
grafico = px.scatter(x= x_plano_saude_2.ravel(), y= y_plano_saude_2)
grafico.add_scatter(x= x_plano_saude_2.ravel(), y= y_plano_saude_2, name= 'Regressão')

In [30]:
x_teste_arvore = np.arange(min(x_plano_saude_2), max(x_plano_saude_2), 0.1)
x_teste_arvore = x_teste_arvore.reshape(-1,1)
x_teste_arvore

array([[18. ],
       [18.1],
       [18.2],
       [18.3],
       [18.4],
       [18.5],
       [18.6],
       [18.7],
       [18.8],
       [18.9],
       [19. ],
       [19.1],
       [19.2],
       [19.3],
       [19.4],
       [19.5],
       [19.6],
       [19.7],
       [19.8],
       [19.9],
       [20. ],
       [20.1],
       [20.2],
       [20.3],
       [20.4],
       [20.5],
       [20.6],
       [20.7],
       [20.8],
       [20.9],
       [21. ],
       [21.1],
       [21.2],
       [21.3],
       [21.4],
       [21.5],
       [21.6],
       [21.7],
       [21.8],
       [21.9],
       [22. ],
       [22.1],
       [22.2],
       [22.3],
       [22.4],
       [22.5],
       [22.6],
       [22.7],
       [22.8],
       [22.9],
       [23. ],
       [23.1],
       [23.2],
       [23.3],
       [23.4],
       [23.5],
       [23.6],
       [23.7],
       [23.8],
       [23.9],
       [24. ],
       [24.1],
       [24.2],
       [24.3],
       [24.4],
       [24.5],
       [24

In [31]:
grafico = px.scatter(x= x_plano_saude_2.ravel(), y= y_plano_saude_2)
grafico.add_scatter(x= x_teste_arvore.ravel(), y= regressor_arvore_saude.predict(x_teste_arvore), name= 'Regressão')

In [32]:
regressor_arvore_casas = DecisionTreeRegressor()
regressor_arvore_casas.fit(x_casas_treinamento, y_casas_treinamento)

DecisionTreeRegressor()

In [33]:
regressor_arvore_casas.score(x_casas_treinamento, y_casas_treinamento)

0.9992712177726063

In [34]:
regressor_arvore_casas.score(x_casas_teste, y_casas_teste)

0.7215854773869667

In [35]:
previsoes = regressor_arvore_casas.predict(x_casas_teste)
previsoes

array([ 288000., 2340000.,  483000., ...,  289000.,  215000.,  205000.])

In [36]:
y_casas_teste

array([ 297000., 1578000.,  562100., ...,  380000.,  268000.,  206000.])

In [43]:
mean_absolute_error(y_casas_teste, previsoes)

100035.18036705737

## Regressão com random forest

In [44]:
x_plano_saude_2

array([[18],
       [23],
       [28],
       [33],
       [38],
       [43],
       [48],
       [53],
       [58],
       [63]], dtype=int64)

In [45]:
y_plano_saude_2

array([  470,   520,   630,   830,  1150,  1530,  2040,  3080,  5100,
       10100], dtype=int64)

In [49]:
from sklearn.ensemble import RandomForestRegressor
regressor_random_forest_saude = RandomForestRegressor(n_estimators= 19)
regressor_random_forest_saude.fit(x_plano_saude_2, y_plano_saude_2)


RandomForestRegressor(n_estimators=19)

In [50]:
regressor_random_forest_saude.score(x_plano_saude_2, y_plano_saude_2)

0.952948036657978

In [53]:
grafico = px.scatter(x= x_plano_saude_2.ravel(), y= y_plano_saude_2)
grafico.add_scatter(x= x_teste_arvore.ravel(), y= regressor_random_forest_saude.predict(x_teste_arvore), name= 'regressão')

In [54]:
regressor_randon_forest_casas = RandomForestRegressor(n_estimators=100)
regressor_randon_forest_casas.fit(x_casas_treinamento, y_casas_treinamento)

RandomForestRegressor()

In [60]:
regressor_randon_forest_casas.score(x_casas_treinamento, y_casas_treinamento)

0.9806505326620872

In [59]:
regressor_randon_forest_casas.score(x_casas_teste, y_casas_teste)

0.8785724990972826

In [62]:
previsoes = regressor_randon_forest_casas.predict(x_casas_teste)
previsoes

array([ 312406.  , 1722623.1 ,  531164.09, ...,  381945.38,  228661.22,
        202101.2 ])

In [63]:
mean_absolute_error(y_casas_teste, previsoes)

67964.49684945543

## Regressão com vetores de suporte

In [64]:
from sklearn.svm import SVR
regressor_svr_saude = SVR(kernel= 'linear')
regressor_svr_saude.fit(x_plano_saude_2, y_plano_saude_2)

SVR(kernel='linear')

In [65]:
grafico = px.scatter(x= x_plano_saude_2.ravel(), y= y_plano_saude_2)
grafico.add_scatter(x= x_plano_saude_2.ravel(), y= regressor_svr_saude.predict(x_plano_saude_2), name= 'regressão')

In [71]:
regressor_svr_saude_polinomial = SVR(kernel= 'poly', degree= 5)
regressor_svr_saude_polinomial.fit(x_plano_saude_2, y_plano_saude_2)

SVR(degree=5, kernel='poly')

In [72]:
grafico = px.scatter(x= x_plano_saude_2.ravel(), y= y_plano_saude_2)
grafico.add_scatter(x= x_plano_saude_2.ravel(), y= regressor_svr_saude_polinomial.predict(x_plano_saude_2), name= 'regressão')

In [79]:
from sklearn.preprocessing import StandardScaler
scaler_x = StandardScaler()
x_plano_saude_2_scaler = scaler_x.fit_transform(x_plano_saude_2)
scaler_y = StandardScaler()
y_plano_saude_2_scaler = scaler_y.fit_transform(y_plano_saude_2.reshape(-1, 1))

In [82]:
regressor_svr_saude_rbf = SVR(kernel= 'rbf')
regressor_svr_saude_rbf.fit(x_plano_saude_2_scaler, y_plano_saude_2_scaler.ravel())

SVR()

In [86]:
grafico = px.scatter(x= x_plano_saude_2_scaler.ravel(), y= y_plano_saude_2_scaler.ravel())
grafico.add_scatter(x= x_plano_saude_2_scaler.ravel(), y= regressor_svr_saude_rbf.predict(x_plano_saude_2_scaler), name= 'regressão')
grafico.show()

In [88]:
novo = scaler_x.transform([[40]])
regressor_svr_saude_rbf.predict(novo)


array([-0.42259356])

In [98]:
scaler_x_casas = StandardScaler()
x_casas_treinamento_scaled = scaler_x_casas.fit_transform(x_casas_treinamento)
scaler_y_casas = StandardScaler()
y_casas_treinamento_scaled = scaler_y_casas.fit_transform(y_casas_treinamento.reshape(-1, 1))


In [99]:
x_casas_teste_scaled = scaler_x_casas.fit_transform(x_casas_teste)
y_casas_teste_scaled = scaler_y_casas.fit_transform(y_casas_teste.reshape(-1, 1))


In [101]:
regressor_svr_casas = SVR(kernel='rbf')
regressor_svr_casas.fit(x_casas_treinamento_scaled, y_casas_treinamento_scaled)

c:\Users\isach\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



SVR()

In [102]:
regressor_svr_casas.score(x_casas_treinamento_scaled, y_casas_treinamento_scaled)

0.8123337393146999

In [103]:
regressor_svr_casas.score(x_casas_teste_scaled, y_casas_teste_scaled)

0.7339158652152076

In [104]:
previsoes = regressor_svr_casas.predict(x_casas_teste_scaled)

In [108]:
previsoes

array([-0.54877296,  3.48844091,  0.01692247, ..., -0.43360248,
       -0.92110462, -1.041454  ])

In [109]:
y_casas_teste_reverse = scaler_y_casas.inverse_transform(y_casas_teste_scaled)
previsoes_inverse = scaler_y_casas.inverse_transform(previsoes)

ValueError: Expected 2D array, got 1D array instead:
array=[-0.54877296  3.48844091  0.01692247 ... -0.43360248 -0.92110462
 -1.041454  ].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

## Regressão com redes neurais

In [110]:
x_plano_saude_2_scaler

array([[-1.5666989 ],
       [-1.21854359],
       [-0.87038828],
       [-0.52223297],
       [-0.17407766],
       [ 0.17407766],
       [ 0.52223297],
       [ 0.87038828],
       [ 1.21854359],
       [ 1.5666989 ]])

In [112]:
from sklearn.neural_network import MLPRegressor
regressor_rna_saude = MLPRegressor(max_iter= 1000)
regressor_rna_saude.fit(x_plano_saude_2_scaler, y_plano_saude_2_scaler.ravel())


MLPRegressor(max_iter=1000)

In [113]:
regressor_rna_saude.score(x_plano_saude_2_scaler, y_plano_saude_2_scaler)

0.9512395968107745

In [115]:
grafico = px.scatter(x= x_plano_saude_2_scaler.ravel(), y= y_plano_saude_2_scaler.ravel())
grafico.add_scatter(x= x_plano_saude_2_scaler.ravel(), y= regressor_rna_saude.predict(x_plano_saude_2_scaler), name= 'regressão')
grafico.show()

In [118]:
novo = [[40]]
novo = scaler_x.transform(novo)
novo

array([[-0.03481553]])

In [ ]:
scaler_y.inverse_transform(regressor_rna_saude.predict(novo))

In [133]:
regressor_rna_casas = MLPRegressor(max_iter= 900, hidden_layer_sizes=(9, 9))
regressor_rna_casas.fit(x_casas_treinamento_scaled, y_casas_treinamento_scaled.ravel())

MLPRegressor(hidden_layer_sizes=(9, 9), max_iter=900)

In [134]:
regressor_rna_casas.score(x_casas_treinamento_scaled, y_casas_treinamento_scaled)

0.8958171102309403

In [135]:
regressor_rna_casas.score(x_casas_teste_scaled, y_casas_teste_scaled)

0.8804012674752026

In [138]:
previsoes = regressor_rna_casas.predict(x_casas_teste_scaled)
previsoes

array([-0.61020709,  2.63746874, -0.02591425, ..., -0.64635127,
       -0.85684503, -0.87181211])

In [139]:
y_casas_teste_inverse = scaler_y_casas.inverse_transform(y_casas_teste_scaled)
previsoes_inverse = scaler_y_casas.inverse_transform(previsoes)

ValueError: Expected 2D array, got 1D array instead:
array=[-0.61020709  2.63746874 -0.02591425 ... -0.64635127 -0.85684503
 -0.87181211].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.